version: "3"
services:
  # Ethereum
  eth:
    image: parity/parity:v2.0.7
    command: "--chain dev --tracing on"
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180
  # Database
  mongo:
    image: mongo
    ports:
     - "27017:27017"
  # Cache
  redis:
    image: "redis:alpine"
  # Daolist
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.web
    ports:
     - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
     - mongo
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.worker
    environment:
     - MONGODB_URI=mongodb://mongo:27017
     - ETH_NODE=ws://eth:8546
     - REDIS_URL=redis://redis:6379
    depends_on:
     - mongo
     - redis
     - eth
