version: "3"
services:
  # Database
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
  # API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.web
    ports:
    - "3000:3000"
    environment:
    - MONGODB_URI=mongodb://mongo:27017
    - ETH_NODE=wss://mainnet.eth.aragon.network/ws
    depends_on:
    - mongo
  # Website
  website:
    build:
      context: ./website
      dockerfile: Dockerfile.frontend
      args:
        API_URL: "http://localhost:3000"
        CHAIN_ID: "1"
    ports:
    - "8888:80"
    depends_on:
    - api

volumes:
  mongo-data:
