version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: Install dependencies in worker
          command: cd worker && npm i
      - run:
          name: Install dependencies in website
          command: cd website && npm i
      - run:
          name: Install dependencies in api
          command: cd api && npm i
      - run:
          name: Run lint on worker
          command: cd worker && npm run lint
      - run:
          name: Run lint on website
          command: cd website && npm run lint
      - run:
          name: Run lint on api
          command: cd api && npm run lint

workflows:
  version: 2
  lint:
    jobs:
      - lint
