version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "worker/package-lock.json" }}-{{ checksum "website/package-lock.json" }}-{{ checksum "api/package-lock.json" }}
      - run:
          name: Dependencies
          command: |
            npm --prefix worker i
            npm --prefix website i
            npm --prefix api i
      - save_cache:
          name: Save Cache
          paths:
            - ./worker/node_modules
            - ./website/node_modules
            - ./api/node_modules
          key: deps-{{ checksum "worker/package-lock.json" }}-{{ checksum "website/package-lock.json" }}-{{ checksum "api/package-lock.json" }}
      - run:
          name: Lint
          command: |
            npm --prefix worker run lint
            npm --prefix website run lint
            npm --prefix api run lint
workflows:
  version: 2
  lint:
    jobs:
      - lint
