version: 2
jobs:
  deps:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "worker/package.json" }}-{{ checksum "website/package.json" }}-{{ checksum "api/package.json" }}
      - run:
          name: Dependencies
          command: |
            npm --prefix worker i
            npm --prefix website i
            npm --prefix api i
      - save_cache:
          name: Save Cache
          paths:
            - ./worker/node_modules
            - ./website/node_modules
            - ./api/node_modules
          key: deps-{{ checksum "worker/package.json" }}-{{ checksum "website/package.json" }}-{{ checksum "api/package.json" }}
  worker_lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "worker/package.json" }}-{{ checksum "website/package.json" }}-{{ checksum "api/package.json" }}
      - run:
          name: Lint
          command: npm --prefix worker run lint
  website_lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "worker/package.json" }}-{{ checksum "website/package.json" }}-{{ checksum "api/package.json" }}
      - run:
          name: Lint
          command: npm --prefix website run lint
  api_lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "worker/package.json" }}-{{ checksum "website/package.json" }}-{{ checksum "api/package.json" }}
      - run:
          name: Lint
          command: npm --prefix api run lint
  worker_test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "worker/package.json" }}-{{ checksum "website/package.json" }}-{{ checksum "api/package.json" }}
      - run:
          name: Test
          command: npm --prefix worker test
  api_test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "worker/package.json" }}-{{ checksum "website/package.json" }}-{{ checksum "api/package.json" }}
      - run:
          name: Test
          command: npm --prefix api test

workflows:
  version: 2
  build_and_test:
    jobs:
      - deps
      - worker_lint:
          requires:
            - deps
      - website_lint:
          requires:
            - deps
      - api_lint:
          requires:
            - deps
      - api_test:
          requires:
            - api_lint
      - worker_test:
          requires:
            - worker_lint
